name: release

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_SOURCE_DIR: ./src
  PROJECT_ARTIFACTS_DIR: ./.dist

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6
      
      - name: Build and pack
        run: dotnet build ${{ env.PROJECT_SOURCE_DIR }} --configuration Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NuGet packages
          path: ${{ env.PROJECT_ARTIFACTS_DIR }}

  publish:
    runs-on: windows-latest
    needs: build
    if: ${{ github.event.release.id }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGet packages
          path: ${{ env.PROJECT_ARTIFACTS_DIR }}

      # note: Settings > Actions > General > Workflow permissions > allow 'Read and write permissions'
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PROJECT_ARTIFACTS_DIR }}/*.*

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6

      - name: Publish to nuget.org
        working-directory: ${{ env.PROJECT_ARTIFACTS_DIR }}
        run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json